steps:
  - label: ":pipeline: Pipeline upload"
    command: buildkite-agent pipeline upload

steps:
label: "Build Go App"
  - commands: 
    - cd hello
    - go build
label: "Run Go App"
  - commands: 
    - ls
    - chmod +x .
    - ./hello Buildkite ftw
    plugins:
      - docker#v5.11.0:
          image: "golang:latest"




