
steps:
 - label: "my go build
   key: "buildmefirst"
   commands:
    - "cd hello"
    - "go build"
    - "ls"


 - label: "execute hello world"
   commands:
     - "chmod +x hello/hello"
     - "./hello/hello John Doe"
   depends_on: ["buildmefirst"]

