steps:
  - label: "Build Go App"
    key: "build"
    commands: 
      - cd hello
      - go build
    plugins:
      - docker#v5.11.0:
          image: "golang:latest"
          volumes:
            - "./hello:/app"  

  - label: "Run Go App"
    depends_on: "build"
    commands: 
      - ls
      - cd hello
      - ls
      - chmod +x hello/hello
      - ./hello/hello buildkite ftw
    plugins:
      - docker#v5.11.0:
          image: "golang:latest"
          volumes:
            - "./hello:/app" 
