steps:
  - label: "Build Go App" # Build go app in docker image
    key: "build"
    commands: 
      - cd hello
      - go build
    plugins:
      - docker#v5.11.0:
          image: "golang:latest"
    artifact_paths:
      - "hello/hello"
            
  - label: "APPROVE ME PLZ" #Approval stage to proceed after build
    key: "manualapproval"
    depends_on: "build"
    block: ":rocket: Are we ready to deploy?"
    prompt: "Who do you want to say hello to?"
  
    fields:
      - text: "Your name"
        key: "name"
        required: true
  - command: echo $(buildkite-agent meta-data get name) # Check to ensure name has passed through

  - label: "Run Go App" # Downloads build and executes binary based off name input
    depends_on: "manualapproval"
    commands: 
      - ls 
      - mkdir goapp
      - buildkite-agent artifact download 'hello/hello' ./goapp
      - cd goapp
      - ls
      - echo $(buildkite-agent meta-data get name)
      - cd hello
      - chmod +x ./hello 
      - ./hello $(buildkite-agent meta-data get name)

