steps:
  - label: "Build Go App"
    key: "build"
    commands: 
      - cd hello
      - go build
    plugins:
      - docker#v5.11.0:
          image: "golang:latest"
          volumes:
            - "./hello:/app"  

steps:
  - block: ":rocket: Are we ready to deploy?"
    depends_on: "build"

  - label: "Run Go App"
    depends_on: "build"
    commands: 
      - cd hello
      - go build
      - chmod +x ./hello
      - ./hello buildkite ftw
    plugins:
      - docker#v5.11.0:
          image: "golang:latest"
          volumes:
            - "./hello:/app" 
