steps:
  - label: "Build Go App"
    key: "build"
    commands: 
      - cd hello
      - go build
      - ls
    plugins:
      - docker#v5.11.0:
          image: "golang:latest"
          artifact_paths:
            - "hello/hello"
            
  - label: "APPROVE ME PLZ"
    key: "manualapproval"
    depends_on: "build"
    block: ":rocket: Are we ready to deploy?"
    prompt: "Who do you want to say hello to?"
    fields:
      - text: "Your name"
        key: "name"
  - command: name.sh 
  - command: echo $(buildkite-agent meta-data get name)

  - label: "Run Go App"
    depends_on: "manualapproval"
    commands: 
      - ls 
      - mkdir goapp
      - buildkite-agent artifact download 'hello/hello' ./goapp'
      - cd goapp
      - ls
      - echo $(buildkite-agent meta-data get name)
      - cd hello
      - chmod +x ./hello 
      - ./hello $(buildkite-agent meta-data get name)

