steps:
  - label: "Build Go App"
    key: "build"
    commands: 
      - cd hello
      - go build
      - ls
      - chmod +x ./hello
      - ./hello buildkite ftw
    plugins:
      - docker#v5.11.0:
          image: "golang:latest"


