steps:
  - label: "Build Go App"
    key: "build"
    commands: 
      - cd hello
      - go build
   
    plugins:
      - docker#v5.11.0:
          image: "golang:latest"
          volumes:
            - "./hello:/app"  
            
  - label: "APPROVE ME PLZ"
    key: "manualapproval"
    depends_on: "build"
    block: ":rocket: Are we ready to deploy?"
    prompt: "Who do you want to say hello to?"
    fields:
      - text: "Your name"
        key: "name"
  - command: name.sh

  - label: "Run Go App"
    depends_on: "manualapproval"
    commands: 
      - cd hello
      - go build
      - chmod +x ./hello
      - echo $(buildkite-agent meta-data get "release-version")
      - ./hello $(buildkite-agent meta-data get name)
    plugins:
      - docker#v5.11.0:
          image: "golang:latest"
          volumes:
            - "./hello:/app" 
